repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
  - id: go-fmt
  - id: validate-toml
  - id: no-go-testing
- repo: git://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0  # or specific git tag
  hooks:
    - id: markdownlint # Configure in .mdlrc
    - id: markdownlint-fix
