name: Quality checks

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.3"
          cache: "npm"

      - name: Node version
        run: node --version

      # cache node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Node dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm i -f

      - name: Build
        run: npm run build

  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Links check
        uses: becheran/mlc@19f75f995fe510740f15221dc82d749af45b522f # v0.14.3
        with:
          args: >
            ./src/master
            -r ./src/.vuepress/public/
            --ignore-links
                https://github.com/codenotary/immudb4dotnet/issues/new
                https://github.com/codenotary/immu-js
                https://twitter.com/intent/tweet*
                https://www.php.net/manual/en/book.pgsql.php
            --match-file-extension

      - name: Check of configuration options list
        run: ./checks/configuration.sh

  examples-check-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - name: Check go examples
        run: ./checks/examples-go.sh
